services:
  traefik:
    image: traefik:v3.3
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.caserver=${LETSENCRYPT_CASERVER:-https://acme-staging-v02.api.letsencrypt.org/directory}"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  web:
    image: ghcr.io/brendanbank/dyndns-route53:latest
    build: .
    expose:
      - 80
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dyndns.rule=Host(`${TRAEFIK_HOSTNAME}`) || Host(`${TRAEFIK_HOSTNAME2}`)"
      - "traefik.http.routers.dyndns.entrypoints=websecure"
      - "traefik.http.routers.dyndns.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dyndns.tls.domains[0].main=${TRAEFIK_HOSTNAME}"
      - "traefik.http.routers.dyndns.tls.domains[0].sans=${TRAEFIK_HOSTNAME2}"
      - "traefik.http.services.dyndns.loadbalancer.server.port=80"
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://loki.bgwlan.nl:3100/loki/api/v1/push"
